pr:
  - master

resources:
  containers:
  - container: node # reusable alias
    image: node:10.16-stretch

jobs:
 - job : a
   container: node
   steps: 
   - script: npm i
   - script: npm run lint
   - script: npm run test-ci
   - task: PublishTestResults@2
     condition: succeededOrFailed()
     inputs:
       testRunner: JUnit
       testResultsFiles: '**/test-results.xml'
       failTaskOnFailedTests: true # Fail the task if there are test failures
    